import shutil
import os
import sys

if __name__ == "__main__":

    # proto_dir is egs/gentle/data, if it doesn't exist, it is created here.
    proto_dir = sys.argv[1]
    if os.path.exists(proto_dir):
        pass
    else:
        os.makedirs(proto_dir)

    lang_path = proto_dir + "/langdir"
    graph_path = proto_dir + "/tdnn_7b_chain_online/graph_pp"
    feats_path = proto_dir + "/feats"

    # 1.deletes all lang related input files that get generated by generateLM.py
    # egs/gentle/data/langdir/*, egs/gentle/data/tdnn../graph../*, if it doesn't exist create it.
    # 2.deletes all feature inputs that get generated on call to automateDecoding.py;
    # empty egs/gentle/data/feats/*, if it doesn't exist create it.
    for path in [lang_path, graph_path, feats_path]:
        if os.path.exists(path):
            shutil.rmtree(path)
        os.makedirs(path)

    # check for final.mdl, tree inside egs/gentle/model/
    # check for lexicon.txt inside egs/gentle/lexicon/
    # if either is not found, raise error
    try:
        if os.path.exists(proto_dir + "/../model"):
            pass
        else:
            os.makedirs(proto_dir + "/../model")
            print(
                "path: ", proto_dir + "/../model doesn't exist but it is created now!"
            )

        if os.path.exists(proto_dir + "/../model/final.mdl") and os.path.exists(
            proto_dir + "/../model/tree"
        ):
            print("Acoustic model files are found: all OK!")
            # copy these files to proto_dir+"/tdnn_7b_chain_online"
            shutil.copy(
                proto_dir + "/../model/final.mdl", proto_dir + "/tdnn_7b_chain_online/"
            )
            shutil.copy(
                proto_dir + "/../model/tree", proto_dir + "/tdnn_7b_chain_online/"
            )
        else:
            print("No final.mdl or tree found in ", proto_dir + "/../model")
    except Exception as error:
        print(error)

    try:
        if os.path.exists(proto_dir + "/../lexicon"):
            pass
        else:
            os.makedirs(proto_dir + "/../lexicon")
            print(
                "path: ", proto_dir + "/../lexicon doesn't exist but it is created now!"
            )
        if os.path.exists(proto_dir + "/../lexicon/lexicon.txt"):
            print("lexicon is found: all OK!")
        else:
            print("No lexicon is found in ", proto_dir + "/../lexicon")
    except Exception as error:
        print(error)
